---
- name: install and configure Docker and on EC2 instance
  hosts: myEC2
  roles:
    - docker

- name: Install and configure SonarQube
  hosts: sonarqube-server
  vars:
    arch_mapping:  # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64
  roles:
    - sonarqube

