name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
    deploy:
        runs-on: [self-hosted]

        # Check if the CI workflow was successful
        if: github.event.workflow_run.conclusion == 'success'