name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
    deploy:
        runs-on: [self-hosted]

        # Check if the CI workflow was successful
        if: github.event.workflow_run.conclusion == 'success'

        steps:
        - name: docker pull image
            # pull the new image form dockerhub and get tag name of this image to update the deployment file with new image tag name
          run: |
            docker pull mahmoudhassan9/nodejs-app:${{ github.sha }}
            export DOCKER_IMAGE_SHA=$(docker inspect --format='{{index .RepoDigests 0}}' mahmoudhassan9/nodejs-app:${{ github.sha }} | awk -F'@' '{print $2}')

        - name: Update Deployment YAML with new tag
          run: |
              sed -i "s|image: mahmoudhassan9/nodejs-app:[a-zA-Z0-9]*|image: mahmoudhassan9/nodejs-app:${DOCKER_IMAGE_SHA}|g" deployment-service.yml
    
        - name: Update kubeconfig
          run: aws eks --region us-east-1 update-kubeconfig --name EKS_CLOUD

        - name: Deploy to EKS
          run: kubectl apply -f deployment-service.yml
          