name: Continuous Integration
on:
  push:
    branches:
      - main


jobs:
  
  build-analyze-push:
    name: Build
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  

